accounts/urls.py
from unicodedata import name
from django.urls import path 
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
]

articles/urls.py
from unicodedata import name
from django.urls import path 
from . import views
app_name = 'articles'

urlpatterns=[
    path('',views.home,name='home'),
    path('article/<int:id>/',views.article,name="article"),
    path('search/',views.search,name='search'),
    path('create/',views.article_create,name='create')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("articles.urls", namespace="articles")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=200,unique=True)
    body = models.TextField()

    def __str__(self):
        return self.title

articles/forms.py
from django import forms 
from .models import Article
class ArticleCreatForm(forms.ModelForm):
    class Meta:
        model = Article
        fields  = ['title','body']
    def clean(self):
        data = self.cleaned_data
        title = data.get("title")
        qs = Article.objects.filter(title=title)
        if qs.exists():
            self.add_error("title",f"this title '{title}' is already in use")
        return data 

# class ArticleCreatForm(forms.Form):
#     title = forms.CharField()
#     body = forms.CharField()

#     def clean_title(self):
#         cleaned_title = self.cleaned_data
#         print(cleaned_title)
#         title = cleaned_title.get("title")
#         if title.lower().strip()=="lol":
#             raise forms.ValidationError("we dont do this here !")
#         print("title",title)
#         return title

accounts/views.py
from multiprocessing import context
from django.shortcuts import redirect, render,reverse
from django.contrib.auth import authenticate,login,logout
# Create your views here.


def login_view(request):
    context={}
    if not request.user.is_authenticated:
        if request.method=="POST":
            username = request.POST.get("username")
            password = request.POST.get("password")
            if username and password:
                user = authenticate(username=username,password=password)
                if user :
                    login(request,user)
                    return redirect(reverse("articles:home"))
                context["error"]="the password or the username is uncorect"
        return render(request,'accounts/login.html',context)
    return redirect(reverse("articles:home"))
def logout_view(request):
    logout(request)
    return redirect(reverse("accounts:login"))

articles/views.py
from multiprocessing import context
from re import T
from wsgiref.util import request_uri
from django.shortcuts import redirect, render,reverse
from .models import Article
from django.contrib.auth.decorators import login_required
from .forms import ArticleCreatForm
# Create your views here.
@login_required
def home(request):
    articles = Article.objects.all()

    context = {
        "articles":articles
    }
    return render(request,"articles/home.html",context)
@login_required
def article_create(request):
    form = ArticleCreatForm()
    if request.method=="POST":
        form = ArticleCreatForm(request.POST)
        if form.is_valid():
            # title = form.cleaned_data.get("title")
            # body = form.cleaned_data.get("body")
            # Article.objects.create(title=title,body=body)
            form.save()
            return redirect(reverse("articles:home"))

    context = {
        'form':form
    }
    return render(request,'articles/create.html',context)
def article(request,id):

    obj = Article.objects.get(id=id)
    context = {
        "article":obj
    }
    return render(request,"articles/detail.html",context)
@login_required
def search(request):
    q = request.GET.get("q")
    if q is not None:
        articles = Article.objects.filter(title__icontains=q)
        if articles.count()==0:
            articles=None
    context = {
        "articles":articles
    }
    return render(request,'articles/search.html',context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}login{% endblock title %}
{% block body %}
<br>
<br>
<br>
<h1>login</h1>
{% if error %}
<div style="color: red;">
{{error}}
</div>
{% endif %}
<form method="post">{% csrf_token %}
    <input name="username" type='text' placeholder="username" />
    <input name="password" type='password' placeholder="password"/>
    <button>login</button>
</form>
{% endblock body %}

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block body %}

<form method="post">
    {% csrf_token %}
        {{form}}
<button>post</button>
</form>
{% endblock body %}

articles/templates/articles/detail.html
{%  extends 'base.html' %}
{% block title  %}{{article.title}}{% endblock title %}

{% block body %}
{{article.body}}
{% endblock body %}

articles/templates/articles/home.html
{% extends 'base.html' %} {% block title %} home {% endblock title %} 
{% block body %}
<div>
  <a href="{% url 'articles:create' %}">create</a>
  <ul>
    {% for article in articles %}
    <li><a href="article/{{article.id}}">{{article.title}}</a></li>
  
    {% endfor %}
  </ul>

</div>
{% endblock body %}

articles/templates/articles/search.html
{% extends 'base.html' %} {% block title %} search  {% endblock title %} 
{% block body %}
<div>
  
  <ul>
      {% if articles %}
    {% for article in articles %}
    <li><a href="{% url 'articles:article' article.id %}">{{article.title}}</a></li>
  
    {% endfor %}
    {% else %}
    <h1>there is no results !</h1>
    {% endif %}
  </ul>

</div>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
  </head>

  <body>
    {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">logout</a>
    {% endif %}
    <form action='/search/' method='GET'>
      <input type='text' name='q'/>
      <button>search</button>
    </form>
    {% block body %} {% endblock body %}
  </body>
</html>